// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.CurrencyAPI.Data;

#nullable disable

namespace Services.CurrencyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231006191351_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6");

            modelBuilder.Entity("Services.CurrencyAPI.Models.Currency", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("current_price")
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("market_cap")
                        .HasColumnType("TEXT");

                    b.Property<int?>("market_cap_rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("price_change_24h")
                        .HasColumnType("TEXT");

                    b.Property<double?>("price_change_percentage_24h")
                        .HasColumnType("REAL");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            id = "bitcoin",
                            name = "Bitcoin",
                            symbol = "btc"
                        },
                        new
                        {
                            id = "ethereum",
                            name = "Ethereum",
                            symbol = "eth"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
